### ISSUE TITLE
Itemfixer removes dyed bed

### ISSUE THREAD

**Issue by ghost** [Dimatert9/ItemFixer#12]
Title

**Comment by Leymooo** [comment]
https://github.com/Dimatert9/ItemFixer/blob/master/src/ru/leymooo/fixer/TextureFix.java#L69-L71
it can not remove this blocks

**Comment by Leymooo** [comment]
![image](https://user-images.githubusercontent.com/8667294/30558464-2beb625a-9cba-11e7-8297-0d08ab4859dc.png)
