### ISSUE TITLE
Itemfixer gets bypassed 

### ISSUE THREAD

**Issue by ghost** [Dimatert9/ItemFixer#14]
There is a bypass for worldedit schematics...

**Comment by Leymooo** [comment]
Can you told me. How schematics with hacked items can be appears in schematics folder? 
To download schematic and place it to WorldEdit folder player need access to your server ftp. After player need permissions to paste this schem. Why just not prevent it?

**Comment by Eyremba** [comment]
@Dimatert9 why don't you just "scan" everything that is pasted with WorldEdit after it is placed on the map/world? (Scan the chunks that are placed by WorldEdit)
