### ISSUE TITLE
Itemfixer gets bypassed

### ISSUE THREAD

**Issue by ghost** [Dimatert9/ItemFixer#15]
again, it gets bypassed by worldedit

The FTP is not accessibile, we have a HTTPD module , those schems gets uploaded by supered ips, 

Some supered IPS might be a rogue/troll that uploads their schems

and no, we can't since the server is free-op

A worldedit bridge plus a schematic itemfixer analyzator when they gets loaded/pasted gets filtered it would be sufficient.

**Comment by ghost** [comment]
@Dimatert9 why don't you just "scan" everything that is pasted with WorldEdit after it is placed on the map/world? (Scan the chunks that are placed by WorldEdit)
--


Quoting @eyremba

**Comment by Leymooo** [comment]
Because it will be very slow. Also if player paste schems with chest and with hacked items in these chests. He can not use these items because they will be filtered when he will try to interact with this items.

**Comment by ghost** [comment]
Ahem, those crash-chest can be broken and it will crash ever player near of them.

Just dont be lazy and do it...
