### ISSUE TITLE
Welp, itemfixer not letting copy in-game items

### ISSUE THREAD

**Issue by ghost** [Dimatert9/ItemFixer#17]
Itemfixer it doesn't let you copy with the scrollweel or any way the in-game item with NBT...

**Comment by ghost** [comment]
It doesn't copy anything from in-game NBT included, it should let people copy it...

**Comment by Leymooo** [comment]
Can you make a video?

**Comment by ghost** [comment]
@Dimatert9 , make one sign with a write, then try to copy it with creative mode, and it wont copy since it deletes his nbt whole, and making the sign empty

**Comment by Leymooo** [comment]
This is normal.

**Comment by ghost** [comment]
@Dimatert9 is not normal, it should Copy the whole sign, NBT included.

We are a free-op server soo...

**Comment by Leymooo** [comment]
Hacked clients can create signs with commands. When someone place the sign and will click to sign, a command will be executed by his name. You can simply add BlockEntityTag to ignore.

**Comment by ghost** [comment]
@Dimatert9 it should clear the harmful NBT , not the whole NBT

**Comment by Leymooo** [comment]
It is not easy and can cause a higher memory usage. Also this plugin is made to block a items that give damage, hp, speed and other atributes and block chests and other items that can hold items in itself. Like chests, furnace, jukebox(all items that can be cloned with crtl+middle click in creative).
