### ISSUE TITLE
Potion issue

### ISSUE THREAD

**Issue by ghost** [Dimatert9/ItemFixer#2]
The plugin is still removing OP potions , and is pretty annoying for allowed servers.

i already deleted the custonPotionEffect filtering...

**Comment by Leymooo** [comment]
Are you sure that it is ItemFixer? Maybe you have ProtocolSupport or ViaVersion?

**Comment by ghost** [comment]
yep, i have both, without itemfixer is allowing them

**Comment by Leymooo** [comment]
What is your spigot/cb version?
I will check it later.

**Comment by ghost** [comment]
1.10.x
@Dimatert9 
If you have skype ill will be glad if you help me to find the issue.
im planning to import the source into the main code of my plugin, but it needs first to get rid of that potion filtering

**Comment by Leymooo** [comment]
I have skype. But my English is not good, because my main language is Russian.

**Comment by Leymooo** [comment]
I cannot reproduce this on 1.10.2 with ItemFixer and ProtocolLib installed. 
https://youtu.be/7kRbDFcbp9M

**Comment by ghost** [comment]
You did, it replaces the potion with uncraftable and it still work, but is annoying when the potions have a custom name

**Comment by Leymooo** [comment]
It is spigot change name. Not itemfixer

**Comment by ghost** [comment]
how to fix it?

when i disable itemfix the potion name doesn't not change

EDIT: is itemfix, because if i check the potion NBT is not working

**Comment by Leymooo** [comment]
it is not itemfixer.

**Comment by ghost** [comment]
@Dimatert9 did you tried to look into item's NBT? 

because the potion effects get removed...

and in my server the NBT: in config is empty.

try inspecting the item NBT after they get filtered.

Skillclient owns a hack for this. or else use a one forge mod, i think is named actuallyaddictions.

**Comment by ghost** [comment]
explain why on splash potion there's some black bubbles and those means no potion effects in those bubbles!

**Comment by Leymooo** [comment]
ItemFixer just remove 'CustomPotionEffects' tag from item. If you remove this tag from config, plugin will stop remove this tag. 
https://youtu.be/7kRbDFcbp9M
Look at video: 0:58. Potion filter is enabled. In creative tab potion has 3 nbt tags. When I move this potion to slot bar, potion has **2** nbt tags.
01:13. Potion filter is disabled. In creative tab potion has 3 nbt tags. After move to slot bar - it has **3** nbt tags. 
1:20. i throw this potion. and effect work.

**Comment by ghost** [comment]
WE DID, that wasnt working!

**Comment by ghost** [comment]
might you can give me your jar you are actual using?

**Comment by Leymooo** [comment]
I am using jar from spigotmc.

**Comment by Leymooo** [comment]
Can you check without ProtocolSupport or ViaVersion

**Comment by ghost** [comment]
I did, im using just protocollib

**Comment by ghost** [comment]
Without viaversion too

**Comment by Leymooo** [comment]
I am really dont know what wrong.
https://youtu.be/di4jXGBBptk
what i do wrong?

**Comment by ghost** [comment]
Mmh, check this version : 

https://www.dropbox.com/s/ox7h4k494juclzf/ItemFixer.jar?dl=0

**Comment by Leymooo** [comment]
With this version a have no problem.
You're definitely sure that it cause by ItemFixer?

**Comment by ghost** [comment]
is itemfixer.

**Comment by Leymooo** [comment]
Okey. Can you wtire again, what problem you have?

**Comment by ghost** [comment]
i said it, when you get a potion without the CustonPotionEffect: in config it still removes it and make the potion name as uncraftable potion...

**Comment by Leymooo** [comment]
Its spigot change name to uncraftable potion.
Are sure that potion effects will remove? 
https://youtu.be/di4jXGBBptk
At 1:59 you can see that, after remove potion effect i cant use item or add new items to slot bar.
If you get potion and can add new  items to slot bar, it mean that it isnt ItemFixer.

**Comment by ghost** [comment]
yeah, it does. stop asking the same question...

Forgot: my plugin wont own a permission manager.

**Comment by Leymooo** [comment]
How i can help you, If I have no problems.
Maybe you can make a video?

**Comment by ghost** [comment]
@Dimatert9 well, maybe teamviewer?

**Comment by Leymooo** [comment]
let's go.

**Comment by marcocorriero** [comment]
554 880 444

pass: fb375s

**Comment by Leymooo** [comment]
I can close this issue?

**Comment by ghost** [comment]
DONT, i found is itemfixer
as i put it back the item got  wiped!

**Comment by ghost** [comment]
DONT, i found is itemfixer
as i put it back the item got renamed againnn!

@Dimatert9

**Comment by Leymooo** [comment]
I think it is not ItemFixer and not Spigot. Because in single player it also change to uncraftable potion.

**Comment by Leymooo** [comment]
Try give potion from console
`give @a potion 1 373 {CustomPotionEffects:[{Id:1,Amplifier:0,Duration:600},{Id:3,Amplifier:0,Duration:600},{Id:5,Amplifier:0,Duration:600},{Id:6,Amplifier:0,Duration:600},{Id:8,Amplifier:0,Duration:600},{Id:10,Amplifier:0,Duration:600},{Id:11,Amplifier:0,Duration:600},{Id:12,Amplifier:0,Duration:600},{Id:13,Amplifier:0,Duration:600},{Id:14,Amplifier:0,Duration:600},{Id:16,Amplifier:0,Duration:600},{Id:21,Amplifier:0,Duration:600},{Id:22,Amplifier:0,Duration:600},{Id:23,Amplifier:0,Duration:600}],display:{Name:"Lucky Potion",Lore:["Nothing to explain once used."]}}`
![image](https://cloud.githubusercontent.com/assets/8667294/24837354/43761f72-1d3b-11e7-82ec-cc6aa4d3a63d.png)

**Comment by ghost** [comment]
Close this, is solved.
there is a new issue.
