### ISSUE TITLE
Конфликты с OldCombatMechanics 

### ISSUE THREAD

**Issue by T1MOXA** [Dimatert9/ItemFixer#8]
https://www.spigotmc.org/resources/oldcombatmechanics-disable-1-9-hit-cooldown.19510/
В частности есть конфликты с модулем "old-armour-strength"

**Comment by Leymooo** [comment]
Данный плагин добавляет на броню - AttributeModifiers. Чтобы не конфликтовал надо добавить этот таг в список игнорируемых. Но если добавить то и смысла тогда от айтем фиксера не будет.
У плагина нету нормально API. Да и добавлять поддержку для каждого плагина, который конфликтует, себе дороже.

**Comment by T1MOXA** [comment]
Понятно )
Спасибо.
