### ISSUE TITLE
A worldedit Crash-chest schem

### ISSUE THREAD

**Issue by ghost** [Dimatert9/ItemFixer#9]
Make it filter worldedit too?

Because there is some crash-chests can be bypassed with worldedit.

**Comment by ghost** [comment]
https://www.dropbox.com/s/lvj4pochyhvesij/0NBTSPLOIT.schematic?dl=0

here the schematic

**Comment by Leymooo** [comment]
How players can get this schematic and load to server??
Dissalowed-blocks in worldedit config dont work?

**Comment by ghost** [comment]
ehm
is a chest in the middle.

and chests are allowed to be pasted with worldedit.

**Comment by Leymooo** [comment]
How players download this schematic to server and paste it?

**Comment by ghost** [comment]
//schem load

**Comment by Leymooo** [comment]
I know how load this schem. How normals players(NOT ME) with permissions can download this schem and paste?

**Comment by marcocorriero** [comment]
No one...

**Comment by ghost** [comment]
Everyone can.

**Comment by Leymooo** [comment]
how?

**Comment by ghost** [comment]
Everyone is OP.

**Comment by Leymooo** [comment]
Can you give command to download schematic from url?

**Comment by ghost** [comment]
There is no commands to download schems, he made it before itemfixer got loaded, and saved as multiple fake names schems, there is just a private online schematic importer that woeks just for admins (supered ips)

**Comment by ghost** [comment]
Hey, updates?
